version: "3.9"

services:
  app:
    image: juniperjeong/joojeobton:latest   # Actions가 푸시한 이미지 사용
    container_name: joojeopton-container
    env_file:
      - .env                                # 서버에만 존재
    ports:
      - "5001:5001"                         # 호스트 5001 → 컨테이너 5001
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
