services:
  app:
    container_name: joojeopton-container
    build: .    # 도커파일로 직접 빌드
    env_file:
      - .env                                # 서버에만 존재
    ports:
      - "5001:5001"                         # 호스트 5001 → 컨테이너 5001
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  mongo_data:
