name: CI/CD - Build on EC2 (no registry)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 & deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /srv/joojeopton

            # 최신 코드
            git pull

            # 안전하게 교체
            docker compose down || true
            docker compose up -d --build

            # 확인
            docker compose ps
            curl -s -I http://127.0.0.1:5001/ || true
