name: SSH Key Test

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=yes \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "echo '✅ SSH connection successful'; hostname"
